name: Deploy to PROD
on:
  push:
    tags:
      - prod-**

jobs:
  deploy: 
    name: Deploy to PROD
    uses: ./.github/workflows/deployment.yml
    with:
      path: prod
    
    
    