on:
  workflow_call:
    inputs:
      enviroment:
        description: ''
        type: string
      path: 
        description: ''
        type: string 
      

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: ${{inputs.enviroment}}
      url: ${{ steps.deployment.outputs.page_url }}
    steps:      
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4

      - name: Install Dependencies
        run: npm ci

      - name: Build Project
        run: npm run build -- --base=/rainbow-relax/${{inputs.path}}
      
      - name: Copy Files
        run: |
          cd dist
          mkdir ${{inputs.path}}
          mv assets ${{inputs.path}}
          mv index.html ${{inputs.path}}
          mv vite.svg ${{inputs.path}}

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Upload entire repository
          path: './dist'
  
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

      # - name: Deploy
      #   uses: peaceiris/actions-gh-pages@v4
      #   with:
      #     github_token: ${{ secrets.GITHUB_TOKEN }}
      #     publish_dir: ./dist