name: Deploy to DEV
on:
  push:
    branches:
      - main
      - fix/mpi-69-background-music 

jobs:
  deploy: 
    name: Deploy to DEV
    uses: ./.github/workflows/deployment.yml
    with:
        path: dev
    