name: Deploy to dev
on:
  push:
    branches:
      - MPI-49  # Cambia a la rama correspondiente


jobs:
  deploy: 
    name: deploy to dev 
    uses: ./.github/workflows/deployment.yml
    with:
        enviroment: github-pages-dev
        path: dev
    