name: Deploy to Firebase DEV

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy to Firebase DEV
    uses: ./.github/workflows/firebase-deployment.yml
    with:
      environment: dev
    secrets: inherit
