name: Deploy to Firebase DEV

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy to Firebase DEV
    environment: develop
    uses: ./.github/workflows/firebase-deployment.yml
    with:
      environment: develop
      deployment_url: https://rainbowrelax-dev.web.app
      firebase_project_id: ${{ vars.FIREBASE_PROJECT_ID }}
      vite_gtag: ${{ vars.VITE_GTAG }}
      base_url: ${{ vars.BASE_URL }}
    secrets: inherit