name: Firebase Deployment Workflow

on:
  workflow_call:
    inputs:
      environment:
        description: "Deployment environment (develop, qa, prod)"
        required: true
        type: string
      deployment_url:
        description: "Deployment URL for the environment"
        required: true
        type: string
      firebase_project_id:
        description: "Firebase Project ID"
        required: true
        type: string
      vite_gtag:
        description: "Google Analytics Tag"
        required: false
        type: string
        default: ""
      base_url:
        description: "Base URL for the application"
        required: false
        type: string
        default: ""

permissions:
  contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install Dependencies
        run: npm ci

      - name: Run Linting
        run: npm run lint

      - name: Build Application
        run: npm run build
        env:
          VITE_GTAG: ${{ inputs.vite_gtag }}
          BASE_URL: ${{ inputs.base_url }}

      - name: Setup Firebase CLI
        run: npm install -g firebase-tools

      - name: Deploy to Firebase Hosting
        run: |
          if [ "${{ inputs.environment }}" = "develop" ]; then
            firebase deploy --only hosting:dev --project $FIREBASE_PROJECT_ID --token $FIREBASE_TOKEN
          elif [ "${{ inputs.environment }}" = "qa" ]; then
            firebase deploy --only hosting:qa --project $FIREBASE_PROJECT_ID --token $FIREBASE_TOKEN
          elif [ "${{ inputs.environment }}" = "prod" ]; then
            firebase deploy --only hosting:prod --project $FIREBASE_PROJECT_ID --token $FIREBASE_TOKEN
          fi
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          FIREBASE_PROJECT_ID: ${{ inputs.firebase_project_id }}

      - name: Set Deployment URL
        id: deployment-url
        run: echo "url=${{ inputs.deployment_url }}" >> $GITHUB_OUTPUT

      - name: Comment Deployment URL
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `🚀 **${{ inputs.environment }} Deployment Complete!**\n\n**URL:** ${{ steps.deployment-url.outputs.url }}\n\n**Environment:** ${{ inputs.environment }}\n**Commit:** ${{ github.sha }}`
            })
