name: Deploy to Firebase PROD

on:
  push:
    tags:
      - prod-**
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy to Firebase PROD
    uses: ./.github/workflows/firebase-deployment.yml
    with:
      environment: prod
    secrets: inherit
    env:
      FIREBASE_PROJECT_ID: ${{ vars.FIREBASE_PROJECT_ID }}
      VITE_GTAG: ${{ vars.VITE_GTAG }}
      BASE_URL: ${{ vars.BASE_URL }}